# Generated by Django 2.1.4 on 2018-12-21 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinaPartes', '0002_auto_20181221_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacacionesprocess',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 21, 20, 39, 46, 954919)),
        ),
    ]
