# Generated by Django 2.1.4 on 2018-12-21 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinaPartes', '0003_auto_20181221_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacionesprocess',
            name='document',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacacionesprocess',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 21, 20, 51, 33, 16410)),
        ),
    ]
