# Generated by Django 2.1.4 on 2018-12-24 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficinaPartes', '0005_auto_20181221_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='oficinapartesprocess',
            name='mejoramigo',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacacionesprocess',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 24, 12, 54, 55, 39976)),
        ),
    ]
